on:
  pull_request:
    types: [opened, synchronize]

jobs:
  solution_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Run tests
        run: |
          go test -v
