on:
  pull_request:
    types: [opened, synchronize]

jobs:
  solution_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
      - name: Run tests
        run: |
          # Get the list of files changed in the pull request
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo $files
